# Copyright (c) 2023, Serhat Şevki Dinçer.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

name: QA

on:
  push:
    branches: [ main, dev ]
permissions:
  contents: read
env:
  GOAMD64: v3
  GOARM64: v8.1,lse

jobs:
  Tests:
    strategy:
      max-parallel: 2
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        go: [ oldstable, stable ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
    - name: Run Tests with Coverage
      run: go test -timeout 1h -v -cover -ldflags '-s -w' -trimpath

  Analysis:
    needs: Tests
    permissions:
      actions: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: stable
    - name: Initialize
      uses: github/codeql-action/init@v3
      with:
        languages: go
    - name: Analyze
      uses: github/codeql-action/analyze@v3

  Tuning:
    needs: Analysis
    if: github.ref_name == 'dev'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: stable
    - name: Tune Params
      run: go test -timeout 3h -tags tuneparam -ldflags '-s -w' -trimpath
